import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#4f2c1d",
        "tertiary": "#7e5443",
        "on-surface": "#1a1c1a",
        "inverse-primary": "#b8cdaa",
        "tertiary-fixed-dim": "#f1baa5",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#301307",
        "on-secondary-container": "#716043",
        "tertiary-fixed": "#ffdbce",
        "on-primary-fixed-variant": "#3a4c31",
        "surface-container-highest": "#e3e2e0",
        "secondary-container": "#f4ddb8",
        "inverse-surface": "#2f312f",
        "surface-container-low": "#f4f3f1",
        "surface-container-high": "#e9e8e5",
        "secondary-fixed": "#f7dfbb",
        "on-background": "#1a1c1a",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#101f09",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b8cdaa",
        "primary-container": "#8fa382",
        "background": "#faf9f6",
        "primary": "#516447",
        "primary-fixed": "#d4e9c4",
        "on-secondary": "#ffffff",
        "on-primary-container": "#283920",
        "surface": "#faf9f6",
        "on-secondary-fixed": "#251a04",
        "secondary": "#6d5c3f",
        "error-container": "#ffdad6",
        "surface-tint": "#516447",
        "surface-container": "#efeeeb",
        "outline": "#74786f",
        "surface-bright": "#faf9f6",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#54452a",
        "tertiary-container": "#c4927e",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e3e2e0",
        "secondary-fixed-dim": "#dac4a1",
        "on-tertiary-fixed-variant": "#633d2d",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f1f1ee",
        "outline-variant": "#c4c8bd",
        "on-surface-variant": "#444840",
        "surface-dim": "#dbdad7",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "1.5rem",
        "full": "9999px",
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
